before_install:
- npm install -g npm
install: npm install
script:
- gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
- "./manage ci"
after_success:
- npm run report-coverage
language: node_js
env:
  matrix:
  - NPM_PUBLISH_BRANCHES="master next"
  global:
    secure: t99tTADylH4pjMicagy55UrS8B6YQzMi3L6sm8vKMWEt21727mdVAvZfu5Y7fac/nE0Es7U3YR/ceF6XV7dQSkzuyUFRsuhRBIWLGoVwpH7b8u7DGJWAVOPX+EJI+9kvybXMNtK75XzfO2G/STtafEzwgij+lbvT79PrKCt0ElHu80MddmalCw7b+CptundAcJXftiG/eNKpROL91Y9Rc1OhUPjJybH1Sjyfe66T8+6UTe2WIXupm2uJlx0dZZ7/ymf7c5m3mi/FWHxLLuC77xX8d8vxSmmg2S6rF95AKyZGOGPZd6gQ6+NajavQaaVbFUYtb7BBwDnpfQB49P/CT6Pd6ZTWkoE4WaobdnblJfInyrjNQU7Oz1e3CczUgXaEVz201UkrxChl0Vz4H+XQQdcdToht5NEvBQ59xKbjjViAwG5WrCPJalwoIMAEHPqVkOombCWssGy+Jduwf8oQG7K5/GzbqCoqXeIU1SSAiRsZ9v7Nl/u7SnNYj/uk4pWsdu0h+owBcesPurYFHcyWt0Z/UsxiAHbFuQvyjlKWVIvOC+XK0kH5DnnYWxPlYFTqZ5w0bNi8qqtGO7iDOSNnM48+opOgp0FgFQpgjwuxysG8yuHbF0k3JowXYguvvZzMizx83dzI0AttIK7cWagIvsuS9uQ/4tHhRjF0f19RVSA=
branches:
  only:
  - master
  - next
  - "/^renovate/.*$/"
  - "/^new-.*$/"
  - "/^feat-.*$/"
  - "/^add-.*$/"
  - "/^change-.*$/"
  - "/^breaking-.*$/"
  - "/^deprecate-.*$/"
  - "/^remove-.*$/"
  - "/^fix-.*$/"
  - "/^sec-.*$/"
  - "/^security-.*$/"
  - "/^perf-.*$/"
  - "/^performance-.*$/"
  - "/^test-.*$/"
  - "/^tests-.*$/"
  - "/^v?\\d+\\.\\d+\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+$/"
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
node_js:
- node
